add label under logo, resolve logo image stretch issue on small device
bioimage-io/archive.bioimage.io pull request #35
Opened 2020-06-25 13:16 UTC by haoxusci

github.svg is repaced with github.png. Because github.svg cannot be modified by max-height:55px

2020-06-25 13:46 UTC, oeway requested changes

2020-06-25 13:46 UTC, oeway commented on src/views/Home.vue
> +                <img :src="item.logo" style="max-height: 55px;" />
There should be another place in the about dialog.

2020-06-26 06:53 UTC, haoxusci commented on src/views/Home.vue
> +                <img :src="item.logo" style="max-height: 55px;" />
now added

2020-06-26 07:23 UTC, oeway commented
Did you test how it looks on small screen when you have long label? I think we should hide the labels when the screen is too small.

Use media queries https://www.w3schools.com/css/css3_mediaqueries_ex.asp to set display to none for small screen.

2020-06-26 08:19 UTC, haoxusci commented
> Did you test how it looks on small screen when you have long label? I think we should hide the labels when the screen is too small.
> 
> Use media queries https://www.w3schools.com/css/css3_mediaqueries_ex.asp to set display to none for small screen.

That makes senses. now I ve set not show the figcaption on small devices, with width less than 500 px

2020-06-26 10:07 UTC, oeway requested changes

2020-06-26 10:07 UTC, oeway commented on src/bulmaswatch.min.css
> +@media screen and (max-width: 500px) {
I would take this out from bulmaswatch since this will affect all the `figcaption`, not sure if  we want that. 

A better solution is to apply it on a class, say `hide-on-small-screen`.

I would define this class in `Home.vue` and apply the class on the two `figcaption`.

2020-06-26 10:47 UTC, haoxusci commented on src/bulmaswatch.min.css
> +@media screen and (max-width: 500px) {
thanks. now added

2020-06-26 21:02 UTC, oeway approved these changes
Looks good, thanks!

2020-06-26 21:04 UTC, oeway commented on src/views/About.vue
> +.hide-on-small-screen {
You can remove these here, because the class defined in Home.vue is global.

2020-06-26 21:04 UTC, oeway commented on src/views/About.vue
> +  .hide-on-small-screen {
Here as well, you don't need this one.

2020-06-26 21:07 UTC, merged